test-relationship:
	g++ ../good_submission/*.cpp test-1-1.cpp --pedantic -o test-relationship
	./test-relationship
	rm test-relationship

test-course:
	g++ ../good_submission/Person.cpp ../good_submission/Course.cpp ../good_submission/Instructor.cpp ../good_submission/Student.cpp test-1-2.cpp --pedantic -o test-course
	./test-course
	rm test-course

test-gradebook:
	g++ ../good_submission/Gradebook.cpp ../good_submission/Grade.cpp test-1-3.cpp --pedantic -o test-gradebook
	./test-gradebook
	rm test-gradebook